[package]
name = "two"
version = "0.0.2"
edition = "2024"
repository = "https://github.com/Toxikuu/2"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
indicatif = "0.17.9"
lazy_static = "1.5.0"
libc = "0.2.169"
log = "0.4.22"
serde = { version = "1.0.216", features = ["derive"] }
toml = "0.8.19"
ureq = "2.12.1"
walkdir = "2.5.0"
