cargo-features = ["edition2024"]

[package]
name = "two"
version = "0.0.31" # updated to ureq 3
edition = "2024"
description = "A source-based package manager for LFS"
repository = "https://github.com/Toxikuu/2"
license = "GPL-3.0"
readme = "README.md"
categories = [ "command line utilities" ]
keywords = [
  "two",
  "2",
  "package manager",
]

[features]
default = [ "upstream" ] # most users won't care about upstream versions (id imagine)
upstream = []

[dependencies]
anyhow = "1.0.95"
indicatif = "0.17.9"
lazy_static = "1.5.0"
libc = "0.2.169"
log = "0.4.22"
toml = "0.8.19"
walkdir = "2.5.0"

[dependencies.clap]
version = "4.5.23"
features = [ "derive" ]

[dependencies.serde]
version = "1.0.216"
features = [
  "derive",
  "rc",
]

[dependencies.ureq]
version = "3.0.2"

[dependencies.log4rs]
version = "1.3.0"
default-features = false
features = [
  "compound_policy",
  "file_appender",
  "chrono",
  "threshold_filter",
]
