[flags]
force = false
quiet = false
verbose = false

# TODO: Allow \x1b, \e, \033 parsing as well in 2
# fn parse_escapes(input: &str) -> String {
#     input.replace("\\x1b", "\x1b")
#     ...
# }
# should work
[message]
danger  = "\u001b[31;1m  "
default = "\u001b[30;3m"
message = "\u001b[36;1m"
prompt  = "\u001b[35;1m"
stderr  = "\u001b[31;3;1m"
stdout  = "\u001b[30;3m"
verbose = "\u001b[34;1m"

[removal]
remove_sources = false
remove_dist = true
prune_logs = true
prune_manifests = true
prune_dist = true

[general]
prefix = "/dry" # the prefix to which packages are installed (/dry for dry runs/testing)
clean_after_build = false
show_bug_report_message = true
show_failure_location = true
check_hashes = false
auto_ambiguity = true
log_level = "trace" # one of: trace, debug, info, warn, error
alphabetize = true

[upstream]
max_threads = 64
stack_size = 128
retries = 3
