[flags]
force = false
quiet = false
verbose = false

[message]
danger  = '\e[31;1m  '
default = '\e[30;3m'
message = '\e[36;1m'
prompt  = '\e[35;1m'
stderr  = '\e[31;3;1m'
stdout  = '\e[30;3m'
verbose = '\e[34;1m'

[removal]
remove_sources = false
remove_dist = true
prune_logs = true
prune_manifests = true
prune_dist = true

[general]
prefix = "/dry" # the prefix to which packages are installed (/dry for dry runs/testing)
clean_after_build = false
show_bug_report_message = true
show_failure_location = true
check_hashes = false
auto_ambiguity = true
log_level = "trace" # one of: trace, debug, info, warn, error
alphabetize = true

[upstream]
max_threads = 64
stack_size = 128
retries = 3
