#!/usr/bin/env bash
# b-32ni (build m32 ninja install) wraps ninja install for m32

source "/usr/share/2/bin/f-core" || exit 211
set -e

DIRS=(
    /usr/lib32
    "${DIRS[@]}"
)

DESTDIR="$BLD/32DEST" ninja "$@" install || die "32DEST ninja install failed"

for DIR in "${DIRS[@]}"; do
  mkdir -pv "$D/$DIR"
  cp -av "$BLD/32DEST/$DIR/"* "$D/$DIR"
done
