#!/usr/bin/env bash
# b-32mi (build m32 make install) wraps make install for m32

source "/usr/share/2/bin/f-core" || exit 211

DIRS=(
    /usr/lib32
    "${DIRS[@]}"
)

make DESTDIR="$BLD/32DEST" "$@" install || die "32DEST make install failed"

for DIR in "${DIRS[@]}"; do
  mkdir -pv "$BLD/D/$DIR"
  cp -Rv "$BLD/32DEST/$DIR/"* "$BLD/D/$DIR"
done
