#!/usr/bin/env bash
# b-cfg (build configure) wraps configure

source "/usr/share/2/bin/f-core" || exit 211

CP="${CP:-.}"

DS="${DS:-true}"

if [ "$DS" == true ]; then
    DS="--disable-static"
else
    unset DS
fi

"$CP/configure" --prefix=/usr $DS "$@" ||
die "configure failed"
