#!/usr/bin/env bash
# b-cmake (build cmake) wraps cmake
# $CP is the configure path

source "/usr/share/2/bin/f-core" || exit 211

cmake \
    -D CMAKE_INSTALL_PREFIX=/usr    \
    -D CMAKE_BUILD_TYPE=Release     \
    -D BUILD_SHARED_LIBS=ON         \
    -D CMAKE_SKIP_INSTALL_RPATH=ON  \
    "$@"                            \
    -W no-dev -G Ninja "${CP:-.}"  ||
die "make failed"
