#!/usr/bin/env bash
# build-ms (build meson setup) wraps meson setup

source "/usr/share/2/bin/f-core" || exit 211

meson setup ${CP:-.}  \
  --prefix=/usr       \
  --buildtype=release \
  --strip "$@"        ||
die "Meson setup failed"
