#!/usr/bin/env bash
# b-pipbuild (build pipbuild) wraps the pip build command

source "/usr/share/2/bin/f-core" || exit 211

pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$@" "$PWD" || die "pip build failed"
