#!/usr/bin/env bash
# b-pipinstall (build pipinstall) wraps the pip install command

source "/usr/share/2/bin/f-core" || exit 211

NAME="${NAME:-$1}"

[ -z "$NAME" ] && die '$NAME is undefined'
[ -z "$1" ] || shift

pip3 install --no-index         \
             --no-deps          \
             --no-user          \
             --root="$PWD/D"    \
             --ignore-installed \
             --no-warn-script-location \
             --find-links dist "$NAME" "$@" ||
die "pip install failed"
