#!/usr/bin/env bash
# e-core (environment core) the core environment exec() sources

set -e # DONT REMOVE THIS

source /usr/share/2/bin/f-core

export CFLAGS="-O2 -march=native -pipe"
export CXXFLAGS="${CFLAGS}"
export MAKEFLAGS="-j$(nproc)"
export FFLAGS="-O2"
export LDFLAGS="-Wl,--as-needed"

export PATH="/usr/share/2/bin:/usr/bin" # import f-path and use those functions if more paths are needed
