#!/usr/bin/env bash
# e-xorg (environment xorg) environment for xorg-related builds

source /usr/share/2/bin/f-path

# it is assumed this will be used alongside b-cfg which includes prefix and disable-static
export XORG_CONFIG="--prefix=/usr                 \
                    --sysconfdir=/etc             \
                    --localstatedir=/var          \
                    --disable-static              \
                    --enable-static=no            \
                    --enable-shared=yes           \
                    --enable-docs=no              \
                    --disable-docs                \
                    --disable-devel-docs          \
                    --without-docs                \
                    --disable-dependency-tracking \
                    --disable-option-checking     \
                    --with-appdefaultdir=/etc/X11/app-defaults"

export XORG_CONFIG_32="--prefix=/usr                  \
                       --sysconfdir=/etc              \
                       --localstatedir=/var           \
                       --disable-static               \
                       --libdir=/usr/lib32            \
                       --host=i686-pc-linux-gnu       \
                       --enable-static=no             \
                       --enable-shared=yes            \
                       --enable-docs=no               \
                       --disable-docs                 \
                       --disable-devel-docs           \
                       --without-docs                 \
                       --disable-dependency-tracking  \
                       --disable-option-checking      \
                       --with-appdefaultdir=/etc/X11/app-defaults"
