#!/usr/bin/env bash
# e-xorg (environment xorg) environment for xorg-related builds

source /usr/share/2/bin/f-path

# it is assumed this will be used alongside b-cfg which includes prefix and disable-static
export XORG_CONFIG="--sysconfdir=/etc --localstatedir=/var"
