#!/usr/bin/env bash
# f-core (functions core) defines core utility functions

die() {
  export -f die
  echo "Death: '$1'" >&2
  exit 1
}

warn() {
  export -f warn
  local width=80

  echo " ### WARNING ###"       >&2
  echo "$1" | fold -s -w $width >&2
  echo " ### WARNING ###"       >&2
}

confirm() {
  local default="${2:-n}"
  local prompt="${1:-Are you sure?}"

  default="${default,,}"

  if [[ "$default" == "y" ]]; then
    prompt+=" [Y/n] "
  else
    prompt+=" [y/N] "
  fi

  while true; do
    read -r -p "$prompt" ans
    ans=${ans,,} # lowercase

    [[ -z "$ans" ]] && ans="$default"

    case "$ans" in
      y|yes) return 0 ;;
      n|no) return 1 ;;
      *) echo "Please answer yes or no" >&2 ;;
    esac
  done
}
