#!/usr/bin/env bash
# m-move (maintainer move) moves a package
#
# Moving packages between repos *is* supported

source /usr/share/2/bin/f-core || exit 211
pushd . > /dev/null

usage() {
  echo -e "\x1b[31;1mUsage: m-move <repo>/<package> <repo>/<package>\x1b[0m" >&2
  echo -e "\x1b[31;1mOrigin, destination, respectively\x1b[0m" >&2
  # you can specify version but it isn't used
  exit 2 # syntax exit code
}

EDITOR="${EDITOR:-nvim}"

[ "$#" -ne 2 ] && usage

[[ "$1" == */*   ]] || usage
[[ "$2" == */*   ]] || usage
[[ "$1" == */*/* ]] && usage
[[ "$2" == */*/* ]] && usage

FROMREPO="${1%%/*}"
FROMNAME="${1#*/}"
FROMNAME="${FROMNAME%%=*}"

TOREPO="${2%%/*}"
TONAME="${2#*/}"
TONAME="${TONAME%%=*}"


echo
echo " ### VARIABLES ### "
echo "FROM REPO: $FROMREPO"
echo "FROM NAME: $FROMNAME"
echo "TO REPO: $TOREPO"
echo "TO NAME: $TONAME"
echo " ### VARIABLES ### "
echo

read -p "Press enter to continue..."

[ -e /usr/ports/"$FROMREPO" ] || die "Nonexistent repo: $FROMREPO"
[ -e /usr/ports/"$TOREPO"   ] || die "Nonexistent repo: $TOREPO"
[ -e /usr/ports/"$FROMREPO/$FROMNAME" ] || die "Origin '$FROMREPO/$FROMNAME' nonexistent"
[ -e /usr/ports/"$TOREPO/$TONAME"     ] && die "Destination '$TOREPO/$TONAME' exists"

mv -v "/usr/ports/$FROMREPO/$FROMNAME" "/usr/ports/$TOREPO/$TONAME"

cd "/usr/ports/$TOREPO/$TONAME"

if [ "$FROMNAME" != "$TONAME" ]; then
  sed -i "0,/^NAME=/s/^NAME=.*/NAME=\"$TONAME\"/" BUILD
  sed -i "0,/^name = /s/^name = .*/name = \"$TONAME\"/" info.lock
fi

# TODO: stop using repo in info.lock as it's never read
if [ "$FROMREPO" != "$TOREPO" ]; then
  sed -i "2,/^repo = /s/^repo = .*/repo = \"$TOREPO\"/" info.lock
fi

"$EDITOR" BUILD
source BUILD

[ "$FROMNAME" == "$TONAME" ] || /usr/share/2/bin/m-gen "$TOREPO/$TONAME"

msg "Committing changes..."

MSG="Moved $FROMREPO/$FROMNAME -> $TOREPO/$TONAME"

git add .
COMMIT=$(git commit -qm "$MSG" && git rev-parse HEAD)

TIMESTAMP=$(date -u "+%Y-%m-%d %H:%M:%S")
echo "[$COMMIT] [$TIMESTAMP] | $MSG" >> CHANGELOG

git add CHANGELOG
git commit -qm "Logged $COMMIT"

if [ "$FROMREPO" != "$TOREPO" ]; then
  msg "Committing changes for origin..."

  cd "/usr/ports/$FROMREPO"
  git rm -r "$FROMNAME"
  git commit -qm "$MSG"
  # this is not changelogged, as it no longer exists
fi

msg "Done!"

popd > /dev/null
