#!/usr/bin/env bash
# m-rev (maintainer revise) revises a package

pushd . > /dev/null

usage() {
  echo 'Usage: m-rev (<repo>/)<package>' >&2
  exit 2 # syntax exit code
}

[ "$#" -ne 1 ] && usage

[[ "$1" == *#*   ]] && usage # options are not supported by this script
[[ "$1" == */*/* ]] && usage
[[ "$1" == *=*   ]] && usage # version must not be specified

# parse repo name if passed
if [[ "$1" == */* ]]; then
  REPO="${1%%/*}"
  NAME="${1#*/}"
else
  NAME="$1"
  REPO="${REPO:-testing}"
fi

VERS="${NAME#*=}"
NAME="${NAME%%=*}"

echo
echo " ### VARIABLES ### "
echo "REPO: $REPO"
echo "NAME: $NAME"
echo " ### VARIABLES ### "
echo

read -p "Press enter to continue..." 

cd "/usr/ports/$REPO/$NAME"

[ -e BUILD ] || { echo 'This package does not exist!' ; exit 1 ;}

mkdir -pv /tmp/2/m-diffs

source BUILD
declare -p > /tmp/2/m-diffs/pre

nvim BUILD

source BUILD
declare -p > /tmp/2/m-diffs/post

# TODO: Add detection for changes that don't need linkhash regeneration
changes=$(diff /tmp/2/m-diffs/p{re,ost} | grep -E 'NAME|VERS|DESC|UPST|SOURCE|EXTRA' | wc -l)
[ "$changes" -gt 0 ] && /usr/share/2/bin/m-gen

git status -s
git add .
git commit -m "$NAME: revisions"
git push

popd > /dev/null
