#!/usr/bin/env bash
# m-rev (maintainer revise) revises a package

pushd . > /dev/null

usage() {
  echo 'Usage: m-rev (<repo>/)<package>' >&2
  # you can specify version but it isn't used
  exit 2 # syntax exit code
}

[ "$#" -ne 1 ] && usage

[[ "$1" == */*/* ]] && usage
[[ "$1" == *=*=* ]] && usage

# parse repo name if passed
if [[ "$1" == */* ]]; then
  REPO="${1%%/*}"
  NAME="${1#*/}"
else
  NAME="$1"
  REPO="${REPO:-main}"
fi

NAME="${NAME%%=*}"

echo
echo " ### VARIABLES ### "
echo "REPO: $REPO"
echo "NAME: $NAME"
echo " ### VARIABLES ### "
echo

read -p "Press enter to continue..." 

cd "/usr/ports/$REPO/$NAME"

[ -e BUILD ] || { echo 'This package does not exist!' ; exit 1 ;}

# regenerate if locked variables are changed
mkdir -pv /tmp/2/m-diffs

source BUILD
declare -p > /tmp/2/m-diffs/pre

nvim BUILD

source BUILD
declare -p > /tmp/2/m-diffs/post

changes=$(diff /tmp/2/m-diffs/p{re,ost} | grep -E 'NAME|VERS|DESC|UPST|SOURCE|EXTRA' | wc -l)
[ "$changes" -gt 0 ] && /usr/share/2/bin/m-gen

git status -s
git add .
git commit -m "$NAME: revisions"
# TODO: consider reading a line at the end of BUILD for custom commit messages

popd > /dev/null
