#!/usr/bin/env bash
# m-upd (maintainer update) updates a package

source /usr/share/2/bin/f-core
pushd . > /dev/null

usage() {
  echo 'Usage: m-upd (<repo>/)<package>=<version>' >&2
  echo 'The version specified becomes the new version'
  exit 2 # syntax exit code
}

EDITOR="${EDITOR:-nvim}"

[ "$#" -ne 1 ] && usage

[[ "$1" == *#*   ]] && usage
[[ "$1" == */*/* ]] && usage
[[ "$1" == *=*=* ]] && usage
[[ "$1" == *=*   ]] || usage # version must be specified

# parse repo name if passed
if [[ "$1" == */* ]]; then
  REPO="${1%%/*}"
  NAME="${1#*/}"
else
  NAME="$1"
  REPO="${REPO:-main}"
fi

VERS="${NAME#*=}"
NAME="${NAME%%=*}"

echo
echo " ### VARIABLES ### "
echo "REPO: $REPO"
echo "NAME: $NAME"
echo "VERS: $VERS"
echo " ### VARIABLES ### "
echo

read -p "Press enter to continue..." 

[ -e /usr/ports/"$REPO" ] || die "Nonexistent repo: $REPO"

cd "/usr/ports/$REPO/$NAME"

NEWVERS="$VERS"
source BUILD
OLDVERS="$VERS"

sed -i "0,/^VERS=/s/^VERS=.*/VERS=\"$NEWVERS\"/" BUILD
"$EDITOR" BUILD
source BUILD # in case the user changes $VERS while in nvim

/usr/share/2/bin/m-gen "$REPO/$NAME"

git status -s
git add .
git commit -m "$NAME: $OLDVERS -> $VERS"

popd > /dev/null
