#!/usr/bin/env bash
# u-val (utility validate) validates the hashes for a file

set -e
file="$1"
knownhash="$2"

[ -z "$knownhash" ] && exit 2

testhash="$(u-hash $file)"

if [[ "$knownhash" == "$testhash" ]]; then
  echo 'Hash is valid'
else
  die "Invalid hash '$testhash' does not equal '$knownhash'"'!'
fi
